[manager]
prepend_keymap = [
	{ on = "i", run = "arrow -1", desc = "Move cursor up" },
	{ on = "k", run = "arrow 1",  desc = "Move cursor down" },
	
	{ on = "j", run = "leave", desc = "Go back to the parent directory" },
	{ on = "l", run = "enter", desc = "Enter the child directory" },
	
	{ on = "I", run = "seek -5", desc = "Seek up 5 units in the preview" },
	{ on = "K", run = "seek 5",  desc = "Seek down 5 units in the preview" },

	{ on = "J", run = "back",    desc = "Go back to the previous directory" },
	{ on = "L", run = "forward", desc = "Go forward to the next directory" },
]

[tasks]
prepend_keymap = [
	{ on = "i", run = "arrow -1", desc = "Move cursor up" },
	{ on = "k", run = "arrow 1",  desc = "Move cursor down" },
]

[select]
prepend_keymap = [
	{ on = "i", run = "arrow -1", desc = "Move cursor up" },
	{ on = "k", run = "arrow 1",  desc = "Move cursor down" },
]

[input]
prepend_keymap = [
	{ on = "j",       run = "move -1", desc = "Move back a character" },
	{ on = "l",       run = "move 1",  desc = "Move forward a character" },
]

[completion]
prepend_keymap = [
	{ on = "<A-i>", run = "arrow -1", desc = "Move cursor up" },
	{ on = "<A-k>", run = "arrow 1",  desc = "Move cursor down" },
]

[help]
prepend_keymap = [
	{ on = "i", run = "arrow -1", desc = "Move cursor up" },
	{ on = "k", run = "arrow 1",  desc = "Move cursor down" },
]


